ci: add Travis CI config with some default settings
FriendsOfShopware/FroshPerformance pull request #3
Opened 2019-01-04 07:02 UTC by DanielRuf

2019-01-04 07:26 UTC, shyim requested changes

2019-01-04 07:26 UTC, shyim commented on .travis.yml
> +  - composer test
This repository currently don't have tests, so there would nothing happends :D

2019-01-04 08:03 UTC, DanielRuf commented on .travis.yml
> +  - composer test
Same in another plugin of FrindsOfShopware ;-)

It exists with 0 if there is no test so this is fine. If there will be tests in the future, the are automatically picked up by PHPUnit

2019-01-04 08:03 UTC, DanielRuf commented on .travis.yml
> +  - composer test
Same in another plugin of FriendsOfShopware ;-)

It exists with 0 if there is no test so this is fine. If there will be tests in the future, the are automatically picked up by PHPUnit

2019-01-04 08:04 UTC, DanielRuf commented on .travis.yml
> +  - composer test
Oh and Travis CI has to be enabled for PRs and commits.

2019-01-04 23:47 UTC, shyim commented on .travis.yml
> +  - composer test
It makes no sense to me. If no tests are available, the ci will everytime fail

2019-01-05 01:02 UTC, DanielRuf commented on .travis.yml
> +  - composer test
Are you sure?
https://github.com/FriendsOfShopware/FroshViewSnapshots
https://travis-ci.org/FriendsOfShopware/FroshViewSnapshots/jobs/368786388#L1266-L1269

https://stackoverflow.com/questions/40421726/phpunit-should-fail-if-no-test-is-executed

2019-01-06 19:18 UTC, shyim commented
I added one for the issue #5 . But thanks for the pull Request

2019-01-06 19:18 UTC, closed without merging